### ISSUE TITLE
table滚动条美化，标题未垂直居中

### ISSUE THREAD

**Issue by rqx110** [ng-alain/delon#390]
- ng-alain version: 7.0.0-rc.4
- Angular version: 7.2.0

开启table滚动条美化功能后，表格标题并未垂直居中。

## 现象
标题未垂直居中：
![image](https://user-images.githubusercontent.com/1829209/51299525-caeb1800-1a63-11e9-9f0d-01b3da46282a.png)

## 重现步骤，Steps to reproduce

开启table滚动条美化功能：`@scrollbar-table-enabled: true;`

## 期望效果
标题垂直居中：
![image](https://user-images.githubusercontent.com/1829209/51299604-04bc1e80-1a64-11e9-9c8f-ca3fdbe8a528.png)

**Comment by cipchk** [comment]
相关原因：https://github.com/NG-ZORRO/ng-zorro-antd/issues/2612

**Comment by rqx110** [comment]
我现在暂时解决方案是强制修改其样式，
```less
@scrollbar-table-enabled: true;
.ant-table-fixed-header .ant-table-scroll .ant-table-header {
    margin-bottom: -@scrollbar-height !important
}
```
